version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.24
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-21-99-237.compute-1.amazonaws.com
            database: d9lg48dqs5n6mn
            ssl: true
            user: ovlonodwjcupto
            password: 070600ab2ef9c0decfb75048134c83f76997ec7bff5ff53aabd505f097412675
            rawAccess: true
            port: '5432'
            migrations: true